// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcXxQjM59emVXOrMyV2n4U9nI4tNvE0z0',
    appId: '1:120825814390:web:66a9b2dfe6199d8150ee57',
    messagingSenderId: '120825814390',
    projectId: 'movie-zone-0101',
    authDomain: 'movie-zone-0101.firebaseapp.com',
    storageBucket: 'movie-zone-0101.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXLvpf2382Ur-L1f-Xq95sCj7ZpGeWSC8',
    appId: '1:120825814390:android:57b62b1d593e459650ee57',
    messagingSenderId: '120825814390',
    projectId: 'movie-zone-0101',
    storageBucket: 'movie-zone-0101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAozaLEYcMhZNeXsXc2G_XY-XAi-2trJSQ',
    appId: '1:120825814390:ios:5b439a391144c80f50ee57',
    messagingSenderId: '120825814390',
    projectId: 'movie-zone-0101',
    storageBucket: 'movie-zone-0101.appspot.com',
    iosBundleId: 'com.example.movieZone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAozaLEYcMhZNeXsXc2G_XY-XAi-2trJSQ',
    appId: '1:120825814390:ios:5b439a391144c80f50ee57',
    messagingSenderId: '120825814390',
    projectId: 'movie-zone-0101',
    storageBucket: 'movie-zone-0101.appspot.com',
    iosBundleId: 'com.example.movieZone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcXxQjM59emVXOrMyV2n4U9nI4tNvE0z0',
    appId: '1:120825814390:web:895b0b155b09974150ee57',
    messagingSenderId: '120825814390',
    projectId: 'movie-zone-0101',
    authDomain: 'movie-zone-0101.firebaseapp.com',
    storageBucket: 'movie-zone-0101.appspot.com',
  );
}
